##
## Copyright (c) 2019-2024
## Pertti Palo, Scott Moisik, Matthew Faytak, and Motoki Saito.
##
## This file is part of Speech Articulation ToolKIT
## (see https://github.com/giuthas/satkit/).
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program. If not, see <http://www.gnu.org/licenses/>.
##
## The example data packaged with this program is licensed under the
## Creative Commons Attribution-NonCommercial-ShareAlike 4.0
## International (CC BY-NC-SA 4.0) License. You should have received a
## copy of the Creative Commons Attribution-NonCommercial-ShareAlike 4.0
## International (CC BY-NC-SA 4.0) License along with the data. If not,
## see <https://creativecommons.org/licenses/by-nc-sa/4.0/> for details.
##
## When using the toolkit for scientific publications, please cite the
## articles listed in README.markdown. They can also be found in
## citations.bib in BibTeX format.
##

# This tells SATKIT which metadata importer to use.
data_source: AAA

# Paths to data, metadata and instructions.
paths:
  # This is where we read the data and metadata from. Leave the data type
  # specific directories empty if everything is in one directory. Dataset's
  # root directory is determined at run time .
  wav:
  textgrid: 
  ultrasound:

  # Strict YAML file specifying recordings to be excluded based 
  # on both prompts and file names.
  exclusion_list: 

  # Where to find the spline import data. This is assumed to be relative to data
  # path.
  spline_config: spline_config.yaml
